### ISSUE TITLE
Conditional Display notification for items currently show

### ISSUE THREAD

**Issue by suzyjstyles** [INCF/artem-is#58]
We currently show a text indicator for hidden questions, but not for unhidden Qs.

This is important because if you change something 'upstream' (e.g., to check what is dependent on an earlier Q) the values are deleted. Perhaps better to include a similar text indicator for dependent visible Qs:

Current: "Conditional questions 69 and 70 are not displayed."
Suggested addition: Conditional questions 69 and 70 are displayed due to data entered at question 68

**Comment by asoskic** [comment]
Edit: there is one case where the users may not be aware of the conditional nature of questions because they are not next to each other, and this is preprocessing software if they select that they did not use the same software for the entire pipeline. However, we have added instructions to clarify this in the "Details" column rather than having to change the code to add the suggested message, which would burden Dejan more.
